check/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from main.views import contabil, fiscal, tributos, index

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'main.views.index.home', name='home'),
    url(r'^upload/', 'main.views.index.upload', name='upload'),
    url(r'^arquivos/', 'main.views.index.lista_arquivo', name='arquivos'),
    url(r'^search/', 'main.views.index.adv_search', name='search'),
    url(r'^search_depara/', 'main.views.index.adv_search_depara', name='search_depara'),

    (r'^grappelli/', include('grappelli.urls')),
    url(r'^detalhe/(?P<arq>\d+)', 'main.views.index.detalhe_arquivo',
        name='detalhe'),
    url(r'^detalhe-depara/(?P<arq>\d+)', 'main.views.index.detalhe_arquivo_depara',
        name='detalhedepara'),
    url(r'^validar/(?P<arq>\d+)', 'main.views.index.valida_arquivo',
        name='validar'),
    url(r'^deparas/(?P<arq>\d+)', 'main.views.index.use_de_para',
        name='de_para'),
    url(r'^donwload/(?P<arq>\d+)', 'main.views.index.download_file',
        name='downloadarquivo'),

    url(r'^deparas/$', 'main.views.index.index_depara', name='home_depara'),

        #Ajax
    url(r'^empresa_por_modulo/?$', 'main.views.index.empresa_por_modulo',
        name='empresapormodulo'),
    url(r'^ajax_index_depara/?$', 'main.views.index.ajax_index_depara',
        name='ajaxindex'),
    url(r'^empresas/?$', 'main.views.index.empresas', name='empresas_ajax'),

    url(r'^documentos/?$', 'main.views.index.documentos',
        name='documentos_ajax'),
    url(r'^doc_depara/?$', 'main.views.index.documentos_depara',
        name='depara_ajax'),


        #URLs De Para Contabil
    url(r'^contabil/nova-conta/?', 'main.views.contabil.create_contabil',
        name='create_contabil'),
    url(r'^contabil/(\d+)/editar/$', 'main.views.contabil.edit_contabil',
        name='edit_contabil'),
    url(r'^contabil/(\d+)/deletar/$', 'main.views.contabil.delete_contabil',
        name='delete_contabil'),

    url(r'^historico/novo-historico/?', 'main.views.contabil.create_historico',
        name='create_historico'),
    url(r'^historico/(\d+)/editar/$', 'main.views.contabil.edit_historico',
        name='edit_historico'),
    url(r'^historico/(\d+)/deletar/$', 'main.views.contabil.delete_historico',
        name='delete_historico'),

        #URLs De Para Fiscal

    url(r'^fiscal-entrada/nova-depara/?',
        'main.views.fiscal.create_fiscal_entrada', name='create_fiscal_entrada'),
    url(r'^fiscal-entrada/(\d+)/editar/$',
        'main.views.fiscal.edit_fiscal_entrada', name='edit_fiscal_entrada'),
    url(r'^fiscal-entrada/(\d+)/deletar/$',
        'main.views.fiscal.delete_fiscal_entrada', name='delete_fiscal_entrada'),

    url(r'^fiscal-filial/novo-depara/?',
        'main.views.fiscal.create_depara_filial',name='create_depara_filial'),
    url(r'^fiscal-filial/(\d+)/editar/$',
            'main.views.fiscal.edit_depara_filial',name='edit_depara_filial'),
    url(r'^fiscal-filial/(\d+)/deletar/$',
            'main.views.fiscal.delete_depara_filial',name='delete_depara_filial'),

    url(r'^fiscal-saida/nova-depara/?', 'main.views.fiscal.create_fiscal_saida',
            name='create_fiscal_saida'),
    url(r'^fiscal-saida/(\d+)/editar/$', 'main.views.fiscal.edit_fiscal_saida', 
            name='edit_fiscal_saida'),
    url(r'^fiscal-saida/(\d+)/deletar/$', 'main.views.fiscal.delete_fiscal_saida',
            name='delete_fiscal_saida'),

       #URLs De Para Tributos

    url(r'^tributo/nova-conta/?', 'main.views.tributos.create_tributos',
            name='create_tributos'),
    url(r'^tributo/(\d+)/editar/$', 'main.views.tributos.edit_tributos',
            name='edit_tributos'),
    url(r'^tributo/(\d+)/deletar/$', 'main.views.tributos.delete_tributos',
            name='delete_tributos'),

        #URLs de Login e LogOff
    url(r'^login/$', 'django.contrib.auth.views.login',
    {'template_name':'login.html'}, 'entrar'),
    url(r'^sair/$', 'django.contrib.auth.views.logout',
        {'next_page': '/login/'}),
    url(r'^admin/', include(admin.site.urls)),

)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('check.main.views.index',
        url(r'^home/$', 'home', name='home'),

)

main/models.py
# encoding: utf-8
#MEDIA_DIR, é a variavel que esta contido o caminho do projeto, encontrando a pasta "media"
from django.core.exceptions import ObjectDoesNotExist
import os
import re
import codecs
MEDIA_DIR = os.path.join(os.path.realpath(os.path.dirname("check")), 'check/media')

from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


#Cada class aqui, representa uma tabela no banco de dados

class UnidadeNegocio(models.Model):
    """
    Classe que representa as Unidades de Negócio
    """
    nome = models.CharField(max_length=100)

    def __unicode__(self):
        return "%s" %(self.nome)

class Cargo(models.Model):
    """
    Classe que representa os Cargos
    """

    nome = models.CharField(max_length=50)

    def __unicode__(self):
        return self.nome

class Colaborador(models.Model):
    """
    Classe que representa os Colaboradores
    """
    user = models.OneToOneField(User)

    nome = models.CharField(max_length=150)
    telefone = models.CharField(max_length=36)
    unidade = models.ForeignKey(UnidadeNegocio)
    cargo = models.ForeignKey(Cargo)

    def __unicode__(self):
        return "%s - %s"%(self.unidade, self.nome)

class Empresa(models.Model):
    """
    Classe que representa as Empresas
    """
    #user = models.OneToOneField(User)

    cnpj = models.CharField(max_length=50)
    cod_questor = models.CharField(max_length=50)
    razao_social = models.CharField(max_length=150)
    unidade_negocio = models.ForeignKey(UnidadeNegocio)
    nome_contato = models.CharField(max_length=170)
    telefone_contato = models.CharField(max_length=50)
    colaborador = models.ManyToManyField(Colaborador, through='Colaborador_Empresa')

    def natural_key(self):
        return (self.razao_social)


    def __unicode__(self):
        return u"%s" %(self.razao_social)

class Colaborador_Empresa(models.Model):
    """
    Classe que representa a o relacionamento entre os Colaboradores 
    e as Empresas.
    Cada Colaborador será responsável por algumas empresas
    e as Empresas poderam ter mais de 1 Colaborador responsável
    """
    colaborador = models.ForeignKey(Colaborador)
    empresa = models.ForeignKey(Empresa)

    def __unicode__(self):
        return "%s" %(self.empresa)

class Layout(models.Model):
    """
    Classe que representa os Layout
    """
    nome = models.CharField(max_length=15)
    representacao = models.CharField(max_length=50)

    def natural_key(self):
        return (self.representacao)

    def __unicode__(self):
        return self.representacao

def tipo_arquivo(filex):
    """
    Verifica a extensao do arquivo enviado para o sistema
    """
    SUPORTADOS = ["csv", "txt", "xml", "xls"]

    name = str(filex)
    name_split = name.split(".")
    if not name_split[-1] in SUPORTADOS:
        raise ValidationError("Arquivo do tipo '%s' não é suportado." %(name_split[-1]))

class Document(models.Model):
    """
    Classe que representa os Documentos.
    Documentos importados pelos Colaboradores, cada documento 
    pertencerá a uma Empresa
    """
    VALIDO = 'V'
    ERROS = 'E'
    N_VALIDADO = 'N'
    STATS_CHOICES = (
            (VALIDO,'Validado'),
            (ERROS,'Com Erros'),
            (N_VALIDADO,'Nao Validado')
            )
    docfile = models.FileField(upload_to="recebidos/", validators=[tipo_arquivo])
    empresa = models.ForeignKey(Empresa)
    layout = models.ForeignKey(Layout)
    status = models.CharField(max_length=15, 
            choices=STATS_CHOICES,default=N_VALIDADO)
    data_envio = models.DateTimeField(auto_now_add=True)

    def natural_key(self):
        return '%s/%s' %(self.empresa, self.layout)

    @classmethod
    def get_content(self, file_id, errors_dict = None):
        """
        Return the content file as Lists
        Retorna o conteudo do arquivo como lista.
        """
        get_file = self.objects.get(pk=file_id)
        instance_file = codecs.open(get_file.docfile.path, 'r','iso8859-1')

        if not errors_dict is None:
            content = ((num_line + 1, line.split(";"), erros) for num_line,
                       line in enumerate(instance_file.readlines())\
                       for num_err,erros in errors_dict.items()\
                       if num_line == num_err)
            instance_file.close()
            return content
        else:
            content = ((num_line +1,line.split(";"))\
                    for num_line,line in enumerate(instance_file.readlines()))
            instance_file.close()
            return content

    def __unicode__(self):
        return "%s - %s" %(self.empresa, self.status)

class DeParaDocumentos(models.Model):
    """
    Classe que representa os Documentos que serao salvos apos a realizacao
    do DE-PARA
    """
    EXPORTADO = 'E'
    NAO_EXPORTADO = 'N'
    STATUS_CHOICES = (
            (EXPORTADO, 'Exportado'),
            (NAO_EXPORTADO, 'Nao Exportado'),
            )
    documento = models.FileField(upload_to="validados/")
    documento_origen = models.ForeignKey(Document)
    status = models.CharField(max_length=20,
            choices=STATUS_CHOICES, default=NAO_EXPORTADO)
    data_envio = models.DateTimeField(auto_now_add=True)
    #empresa = models.ForeignKey(Empresa)

    def natural_key(self):
        return (self.documento_origen)

    def __unicode__(self):
        return "%s" %(self.documento)

    @classmethod
    def get_content(self, file_id):
        """ 
            Return the content file as Lists 
            Retorna o conteudo do arquivo como lista.
        """
        get_file = self.objects.get(pk=file_id)
        instance_file = codecs.open(get_file.documento.path,
                'r', 'iso8859-1')

        content = ((num_line+1,line.split(";")) for num_line,line in
                   enumerate(instance_file.readlines()))
        instance_file.close()

        return content

class Padrao(models.Model):
    """
    Classe que representa os Padroes.
    Os padroes são as sequencias que cada layout terá.
    será salvo os 'formatos' como REGEX e também será
    salvo a ordem desse REGEX cadastrado
    """
    formato = models.CharField(max_length=200)
    ordem = models.IntegerField()
    layout = models.ManyToManyField(Layout, through='Layout_Padrao')

    def __unicode__(self):
        return self.formato

class Layout_Padrao(models.Model):
    """
    Classe que representa o relacionamento entre a
    classe Layout e Padrao.
    Os Padroes terão, em vários Layouts, ordens diferentes
    """
    layout = models.ForeignKey(Layout)
    padrao = models.ForeignKey(Padrao)

    def __unicode__(self):
        return "%s" %(self.padrao)

class ContasLancaCont(models.Model):
    """
    Classe que representa as Contas Lançamentos Contabil
    Faz parte dos DE-PARAS
    """
    de = models.CharField(max_length=40)
    para = models.CharField(max_length=40)
    empresa = models.ForeignKey(Empresa)

    def __unicode__(self):
        return "%s" %(self.empresa)

class HistoricoLancaCont(models.Model):
    """
    Classe que representa os Historicos Lançamentos Contabil
    Faz parte dos DE-PARAS
    """
    de = models.CharField(max_length=40)
    para = models.CharField(max_length=40)
    empresa = models.ForeignKey(Empresa)
    def __unicode__(self):
        return "%s" %(self.de)

class ImpostoDePara(models.Model):
    ESTADUAL = 'E'
    MUNICIPAL = 'M'
    FEDERAL = 'F'
    TIPO_IMPOSTO = (
            (ESTADUAL, 'Estadual'),
            (MUNICIPAL, 'Municipal'),
            (FEDERAL, 'Federal'),
            )
    banco = models.CharField(max_length=100)
    conta = models.CharField(max_length=100)
    agencia = models.CharField(max_length=100)
    tb = models.CharField(max_length=20, verbose_name="Tabela Contábil")
    empresa = models.ForeignKey(Empresa)
    tipo = models.CharField(max_length=5, choices=TIPO_IMPOSTO)
    imposto = models.CharField(max_length=100)

    def __unicode__(self):
        return "%s" %(self.de)

class CodImpostoDP(models.Model):

    RETIDO = 'R'
    NAO_RETIDO = 'N'
    FLAG_RETIDO = (
        (RETIDO, 'Retido'),
        (NAO_RETIDO, 'Não Retido'),
    )
    imposto = models.CharField(max_length=100)
    codigo = models.CharField(max_length=100)
    variacao = models.CharField(max_length=100)
    retido = models.CharField(max_length=6,choices=FLAG_RETIDO,
        default=NAO_RETIDO)
    tb = models.CharField(max_length=100)

class DuplicatasDeParaEntrada(models.Model):
    """
    Classe que representa as Duplicatas de Entrada
    Faz parte dos DE-PARAS
    """
    banco = models.CharField(max_length=100)
    agencia = models.CharField(max_length=100)
    conta = models.CharField(max_length=100)
    tb = models.CharField(max_length=20, verbose_name="Tabela Contábil")
    empresa = models.ForeignKey(Empresa)

    class Meta:
        unique_together = (('banco','agencia','conta','empresa'),)

    def __unicode__(self):
        return "%s, %s - %s" %(self.empresa, self.banco, self.tb)

class DuplicatasDeParaSaida(models.Model):
    """
    Classe que representa as Duplicatas de Saída
    Faz parte dos DE-PARAS
    """
    banco = models.CharField(max_length=100)
    agencia = models.CharField(max_length=100)
    conta = models.CharField(max_length=100)
    tb = models.CharField(max_length=20, verbose_name="Tabela Contábil")
    empresa = models.ForeignKey(Empresa)

    class Meta:
        unique_together = (('banco','agencia','conta','empresa'),)

    def __unicode__(self):
        return "%s, %s - %s" %(self.empresa, self.banco, self.tb)

class DeParaFilial(models.Model):
    de = models.CharField(max_length=100)
    para = models.CharField(max_length=100)
    empresa = models.ForeignKey(Empresa)

    @classmethod
    def depara_filial(self, *args):
        de_arg, empresa_arg = args[0], args[1]

        try:
            result = self.objects.get(de__exact=de_arg, empresa__exact=empresa_arg)
            return result

check/templates/base.html
<!DOCTYPE html>
{% load bootstrap_toolkit %}
<html>
    <head>
        <meta charset="utf-8" />
        <title>EDI-Rui Cadete</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet"/>

        <link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet"/>
        <link href="{{ STATIC_URL }}css/datepicker.css" rel="stylesheet" />
        <style type="text/css">
            #nomeusuario { float : right; }
            .span12{
                background-color: #fff;
                border: 1px solid #e5e5e5;
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
                -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
            }
            body { background-image:url({{ STATIC_URL}}img/cream_pixels.png); }
        </style>
    </head>
    <body>
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <script src="{{ STATIC_URL }}js/jquery.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap.min.js" ></script>
        <script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap-datepicker.pt-BR.js"
        charset="UTF-8" ></script>
        {% block extra_js %}
        {% endblock %}
        <script type="text/javascript">
        $().ready(function(){
          {% block js %}

          {% endblock %}
        });
        </script>

        <div class="container">
        <div class="masthead">
          <h3 class="muted">IntegraSis</h3>
        </div>
        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <ul class="nav">
              {% if user.is_authenticated %}
                <li class="text-center">
                  <a href="/">Inicio</a>
                </li>
                <li class="text-center">
                  <a href="/upload">Importar</a>
                </li>
                <li class="text-center">
                  <a href="/arquivos">Arquivos</a>
                </li>
                <li class="text-center">
                  <a href="/deparas">De-Para</a>
                </li>
                <li class="text-center">
                  <a href="/sair">Sair</a>
                </li>
              {% else %}
                <li class="text-center">
                  <a href="{% url 'entrar' %}">Login</a>
                </li>
              {% endif %}
            </ul>
            <ul class="nav pull-right">
              {% if user.is_authenticated %}
                <li>
                  <a class="muted" href="#">Bem Vindo - {{ user.first_name}} {{ user.last_name }}</a>
                </li>
              {% endif %}
            </ul>
        </div>
      </div>

        {% if user.is_authenticated %}
          {% block breadcrumb %}
            <ul class="breadcrumb">
              <li><a href="/">Inicio</a> <span class="divider">/</span></li>
            </ul>
          {% endblock %}
        {% endif %}
        <div class="row">
          <div class="span12">
            {% block conteudo %}
            {% endblock %}
          </div>
        </div>
  </div>

  </body>
</html>

check/templates/index.html
{% extends 'base.html' %}

{% block conteudo %}

    <div class="span8 offset2">
        <img src="{{ STATIC_URL }}img/macroprocesso.jpg" alt="">
    </div>
{% endblock %}

check/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap_toolkit %}
{% bootstrap_stylesheet_tag %}
{% bootstrap_stylesheet_tag "responsive" %}

{% block conteudo %}
<style>
      .form-signin {
        max-width: 245px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
    .form-signin-heading{
        width: 310px;
        padding: 10px;
        margin: 0 auto;
      }
</style>

        <form class="form-signin" method="POST" >
		{% csrf_token %}
            <h3 class="form-signin-heading">Acesso ao Sistema</h3>
            <div class="input-prepend">
                <span class="add-on">
                    <i class="icon-user"></i>
                </span>
                {{ form.username }}
            </div>
            <div class="input-prepend">
                <span class="add-on">
                    <i class="icon-lock"></i>
                </span>
                {{ form.password }}
            </div>
            <button class="btn-u btn-primary pull-right" type="submit">Entrar</button>
            <br />
       </form>
{% endblock %}
        {% for field in form %}
            {{ field.errors }}
            {{ field.label_tag }}{{ field }}
        {% endfor %}

check/templates/sair.html
{% extends "base.html" %}
{% block conteudo %}
<div class="hero-unit">
<h3>Voce saiu do sistema. Obrigado e volte sempre!</h3>
</div>
{% endblock %}

check/templates/upload.html
{% extends 'base.html' %}
{% block extra_js %}
    <script src="{{ STATIC_URL }}js/upload_p.js"></script>
{% endblock %}
{% block js %}
  $('#myTab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
  });
  $("#addfile").click(function(){
    $("#id_docfile").click();
    return false;
  });

  $('input:file').change(function(e){
    var f = e.target.files, len = f.length;
    for (var i=0; i<len; i++) {
        var file_name = f[i].name;
        $('#showname').html(file_name);
    }
  });
{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="/">Inicio</a> <span class="divider">/</span></li>
    <li class="active">Importar</li>
 </ul>
 {% endblock %}

{% block conteudo %}
<style>

#id_docfile {
    /* Note: display:none on the input won't trigger the click event in WebKit.
        Setting visibility: hidden and height/width:0 works great. */
    visibility: hidden;
    width: 0;
    height: 0;

}
#fileSelect {
    /* style the button any way you want */
}

</style>

<div class="tabbable">
  <ul class="nav nav-tabs" id="my-tab">
    <li class="active"><a href="#tab1" data-toggle="tab">Importar Arquivo</a></li>
    <li><a href="#tab2" data-toggle="tab">Arquivos Importados</a></li>
  </ul>
  <div id="myTabContent" class="tab-content">
    <div class="tab-pane fade in active" id="tab1">
        {% if error %}
            {{ error }}
        {% endif %}
        <form action="{% url 'upload' %}" method="post" class='form-inline' enctype="multipart/form-data" id="formulario">
            {% csrf_token %}
            {% if messages %}
              {% for message in messages %}
              <div class="alert alert-success">
                    {{ message }}
              </div>
              {% endfor %}
            {% endif %}

            {% if form.errors %}
                <div class="alert alert-danger">
                    {{ form.empresa.label_tag }} :{{ form.empresa.errors }}
                    {{ form.layout.label_tag }} : {{ form.layout.errors }}
                    {{ form.docfile.label_tag }} : {{ form.docfile.errors }}
                </div>
            {% endif %}

                <div id="forminput formset">
                  {{ form.empresa.label_tag}} : {{ form.empresa }}
                  {{ form.layout.label_tag }} : {{ form.layout }} 
                  {{ form.docfile }}
                </div>
            <br />
            <button id="addfile" class="btn btn-success fileinput-button">
                <i class="icon-plus"></i>
                <span id="showname">Escolher Arquivo</span>
            </button>

            <button type="submit" class="btn btn-primary start">
                <i class="icon-upload"></i>
                <span>Importar</span>
            </button>
        </form>
    </div>

    <div class="tab-pane fade" id="tab2">
        {% include "arquivos/search_arquvios.html" %}
        <table id="empresas_td" class='table table-striped'>
            <tr>
              <th>#</th>
              <th>Nome do Documento</th>
              <th>Empresa</th>
              <th>Layout</th>
              <th>Data de Importação</th>
            </tr>

       <table>
    </div>
  </div>
</div>


{% endblock %}